#!/usr/bin/env python2
# coding=UTF-8
"""Defines abstract base classes for all kinds of bots"""
import logging, random, shlex, subprocess, time
from abc import ABCMeta, abstractmethod
from blinker import signal
from threading import Thread, current_thread
from twisted.internet import reactor
from twisted.internet.task import LoopingCall
from twisted.python import log

from resources import emu_config


class Runnable(object):
    """A class that executes code, similar to the Java class of the same name"""
    __metaclass__ = ABCMeta

    def __init__(self, name=""):
        self.stopthread = False
        self.name = name
        self.processes = []  # A list of processes that can be stopped via terminate()

        signal('start').connect(self.start)
        signal('start ' + name).connect(self.start)
        signal('stop').connect(self.stop)
        signal('stop ' + name).connect(self.stop)

    @abstractmethod
    def start(self):
        """Starts the runnable so that it will perform its work. This may also be invoked by sending a start signal."""

    @abstractmethod
    def stop(self):
        """Stops the runnable so that it will not perform any further work until restartet.
        Its Thread may now safely be joined without the thread invoking join being blocked.
        This can alternatively be invoked by sending a stop signal."""


class CommandExecutor(Runnable):
    """Executs a command every x seconds"""
    __metaclass__ = ABCMeta

    def __init__(self, name="", pauseBetweenDuties=emu_config.botcommand_timeout):
        """:param pauseBetweenDuties: How long to wait between invocations of performDuty()"""
        Runnable.__init__(self, name)
        self.pauseBetweenDuties = float(pauseBetweenDuties)
        self.lc = LoopingCall(self.performDuty)

    def start(self):
        """Starts the runnable, so that it regularly calls performDuty()"""
        logging.debug("Started performing duties every %d seconds" % self.pauseBetweenDuties)
        observer = log.PythonLoggingObserver()
        observer.start()

        lcDeferred = self.lc.start(float(self.pauseBetweenDuties))
        lcDeferred.addErrback(self.errback)

        reactor.run(installSignalHandlers=0)

    @abstractmethod
    def performDuty(self, args):
        """Does the actual work. Is called regularly and should be implemented by subclasses."""

    def stop(self):
        """Stops performDuty() from being called"""
        logging.debug("Stopping %s" % self.name)
        if self.lc.running:
            self.lc.stop()
        reactor.stop()

    def errback(self, failure):
        """Given to defereds to report errors"""
        logging.warning("%s in %s: %s" % (failure.type, self.name, failure.getErrorMessage()))


class AbstractBot(CommandExecutor):
    """The abstract base class for all bots in the simulated botnets"""
    __metaclass__ = ABCMeta

    def __init__(self, peerlist=[], desinfect_timeout=10, probability_of_disinfection=0, name=""):
        CommandExecutor.__init__(self, name=name)
        assert isinstance(peerlist, list), "type(peerlist): %s" % type(peerlist)

        self.peerlist = peerlist
        self.id = random.randint(1, 100000)
        self.disinfect_timeout = desinfect_timeout
        self.probability_of_disinfection = probability_of_disinfection

    def stop(self, sender=None):
        """Shuts the bot down."""
        logging.info("Bot was stopped via signal from %s" % sender)
        CommandExecutor.stop(self)
        for proc in self.processes:
            proc.terminate()
            # proc.kill()

    def listenForIncomingNoiseTraffic(self):
        """Receives the trafic generated by _sendOutRandomTraffic(). This should run on every Node, so we can choose targets at random."""
        recvprocess = subprocess.Popen(shlex.split("ITGRecv"))
        self.processes.append(recvprocess)
        recvprocess.wait()

def executeBot(bot, pauseBetweenDuties):
    """Helper method for executing the bot in a new thread.
    :param bot: The bot that shall be started.
    :param pauseBetweenDuties: How long to wait between invocations of performDuty()"""
    assert isinstance(bot, Runnable)
    bot.start(pauseBetweenDuties=pauseBetweenDuties)
